### ISSUE TITLE
Find doesn't work in annotator view

### ISSUE THREAD

**Issue by joshunger** [ryu1kn/vscode-annotator#16] opened 2017-12-31 13:06 UTC
Find doesn't work in annotator view. :(

1. `CMD+SHIFT+P`
2. Annotator: Annotate the current file
3. Try `CMD+F`

EXPECTING: Find appears.
ACTUAL: Nothing happens.

**Comment by ryu1kn** [comment] 2018-01-01 00:43
Hmm... I can't reproduce it. With step 3, I could search text in the annotation view

<img width="849" alt="screen shot 2018-01-01 at 11 25 49 am" src="https://user-images.githubusercontent.com/1505715/34464833-9643464e-eee6-11e7-8626-d9b4aba87d2b.png">

Is searching webview contents working at all in the first place? https://code.visualstudio.com/updates/v1_15#_search-in-markdown-preview

**Comment by joshunger** [comment] 2018-01-01 00:55
🤔 Version is 1.19.  Searching in a `README.md` works.  What other information can I provide?

**Comment by ryu1kn** [comment] 2018-01-01 05:43
> Searching in a `README.md` works

Thanks for checking it. That sounds promising. But then what could go wrong...? Which OS are you using?

**Comment by joshunger** [comment] 2018-01-01 11:55
![image](https://user-images.githubusercontent.com/2301847/34467467-e9eb79c4-eeaf-11e7-89f9-665024bf7926.png)

**Comment by ryu1kn** [comment] 2018-01-01 22:00
Thanks. I'm also using mac.

I'm not sure if it's because of annotator or something else. Search in annotation view is not provided by Annotator, and it's just benefitting _search in markdown preview_ feature introduced in vscode 1.15.

Following things might give us some more insights...

* Select **Toggle Developer Tools** and see there are any error logs on console
* Disable all extensions except Annotator and see if the problem persists
* Create a simple extension that uses [`vscode.previewHtml`](https://code.visualstudio.com/docs/extensionAPI/vscode-api-commands) command and see if search works on the HTML contents

**Comment by ryu1kn** [comment] 2018-03-08 08:36
Closing this...

**Closed as completed by ryu1kn** 2018-03-08 08:36 UTC
Labels: needs more info
